[template]
src   = "confd_settings.py"
dest  = "/templates/confd_settings.py"
uid = 1000
gid = 1000
mode  = "0640"
keys = [
  "/deis/controller",
  "/deis/cache",
  "/deis/database",
  "/deis/registry",
  "/deis/domains",
]
check_cmd = "/app/bin/check"
reload_cmd = "/app/bin/reload"
