[template]
src   = "confd_settings.py"
dest  = "/templates/confd_settings.py"
uid = 1000
gid = 1000
mode  = "0640"
keys = [
  "/deis/controller",
  "/deis/database",
  "/deis/registry",
  "/deis/domains",
  "/deis/platform",
  "/deis/scheduler",
  "/deis/logs",
]
reload_cmd = "/app/bin/reload"
