[template]
src   = "check-repos"
dest  = "/home/git/check-repos"
uid = 0
gid = 0
mode  = "0755"
keys = [
  "/deis/services",
  "/deis/registry",
]
reload_cmd = "/home/git/check-repos"
check_cmd = "/app/bin/check {{ .src }}"
