[template]
src   = "pg_hba.conf"
dest  = "/etc/postgresql/9.3/main/pg_hba.conf"
uid = 101
gid = 104
mode  = "0640"
keys = [
  "/deis/database",
]
check_cmd = "/app/bin/check"
reload_cmd = "/usr/local/bin/reload"
