[template]
src   = "reload"
dest  = "/usr/local/bin/reload"
owner = "root"
group = "root"
mode  = "0755"
keys = [
  "/deis/database",
]
check_cmd = "/app/bin/check"
reload_cmd = "/usr/local/bin/reload"
